# Generated by Django 5.1.7 on 2025-03-22 23:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="owner",
            new_name="owner_id",
        ),
    ]
