# Generated by Django 5.1.7 on 2025-03-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_rename_owner_task_owner_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="completed_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
