# Generated by Django 5.1.7 on 2025-03-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_alter_task_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
